# Generated by Django 5.1.1 on 2024-09-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arreglos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorias')),
            ],
        ),
    ]
