# Generated by Django 5.1.1 on 2024-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_arreglos'),
    ]

    operations = [
        migrations.AddField(
            model_name='arreglos',
            name='ImgUrl',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
