# Generated by Django 5.1.1 on 2024-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_arreglos_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='arreglos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
