# Generated by Django 5.1.1 on 2024-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_arreglos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='arreglos',
            name='diponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
