# Generated by Django 5.1.1 on 2024-09-30 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fechaenvio',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='horaEnvio',
            field=models.TimeField(default=datetime.datetime(2024, 9, 30, 15, 26, 26, 31362, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
