# Generated by Django 5.1.1 on 2024-09-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pedido_fechaenvio_pedido_horaenvio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
