# Generated by Django 5.1.1 on 2024-09-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='horaEnvio',
        ),
    ]
