# Generated by Django 5.1.1 on 2024-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_pedido_horaenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mensaje',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
