# Generated by Django 5.1.1 on 2024-10-22 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pedido_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='arreglo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.arreglos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='compras_tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
                ('fechaentrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('arreglo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.arreglos')),
            ],
        ),
    ]
