# Generated by Django 5.1.1 on 2024-10-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pedido_arreglo_compras_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='arreglo',
        ),
    ]
