# Generated by Django 5.1.1 on 2024-10-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arreglo',
            name='diponibilidad',
        ),
        migrations.AddField(
            model_name='arreglo',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
