# Generated by Django 5.1.1 on 2024-11-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_arreglo_diponibilidad_arreglo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
