# Generated by Django 5.1.1 on 2024-11-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_pedido_total_pagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='muicipio',
            new_name='municipio',
        ),
    ]
